# Generated by Django 5.1.1 on 2024-11-14 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_delete_cart_order'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('product_quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fianl_total', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('society', models.CharField(max_length=100)),
                ('apartment_number', models.CharField(max_length=100)),
                ('card_payment', models.BooleanField(default=False)),
                ('upi_payment', models.BooleanField(default=False)),
                ('cash_payment', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.productmodel')),
            ],
        ),
    ]
