# Generated by Django 5.1.1 on 2024-11-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_order',
            name='fianl_total',
        ),
    ]
