# Generated by Django 5.1.1 on 2024-11-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_cart_order_fianl_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_order',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
