# Generated by Django 5.1.1 on 2024-11-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_cart_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_order',
            name='comapny_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart_order',
            name='comapny_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
