# Generated by Django 5.1.1 on 2024-11-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_cart_order_comapny_id_cart_order_comapny_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='is_comapny_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='is_normal_user',
            field=models.BooleanField(default=False),
        ),
    ]
