# Generated by Django 5.1.1 on 2024-11-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customermodel_is_comapny_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='comapny_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='comapny_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
