# Generated by Django 5.1.1 on 2024-11-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customermodel_comapny_id_customermodel_comapny_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_order',
            old_name='comapny_id',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='cart_order',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
