# Generated by Django 5.1.1 on 2024-11-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_rename_comapny_id_cart_order_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
