# Generated by Django 5.1.1 on 2024-11-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_cart_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_order',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
