# Generated by Django 5.1.1 on 2024-11-21 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_staff_staffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='punch_in',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='punch_out',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='date',
            field=models.DateField(),
        ),
    ]
