# Generated by Django 5.1.1 on 2024-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_staffattendance_punch_in_staffattendance_punch_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffattendance',
            name='punch_in',
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='punch_out',
            field=models.TimeField(),
        ),
    ]
