# Generated by Django 5.1.1 on 2024-11-21 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_staffattendance_punch_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='punch_in',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
