# Generated by Django 5.1.1 on 2024-11-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_staffattendance_punch_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='punch_in',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='punch_out',
            field=models.TimeField(blank=True),
        ),
    ]
