# Generated by Django 5.1.1 on 2024-11-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_staffattendance_punch_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
